name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      TG_BOT_TOKEN: "some_token"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Check linters
        run: |
          pre-commit run -a

      - name: Mypy
        run: |
          mypy --config-file pyproject.toml


  unit-tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: sqlite:///./ci.db
      APP_ENV: test
      TG_BOT_TOKEN: "some_token"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pytest (unit)
        run: |
          pytest -q -m "not integration"


  integration-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
          POSTGRES_DB: video
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U app -d video"
          --health-interval 5s
          --health-timeout 5s
    env:
      APP_ENV: test
      DATABASE_URL: postgresql+psycopg://app:app@localhost:5432/video
      TG_BOT_TOKEN: "some_token"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run integration tests
        run: |
          pytest -q -m integration
